swarm/storage: fix test timeout with -race by increasing mget timeout
`go test -race` might significantly increase test run time (~2-10x).
`-race` caused the following tests to time out both locally and on
the CI. So I doubled the timeout.

--- FAIL: TestDbStoreCorrect_1k (16.88s)
    common_test.go:193: testStore failed: timed out after 5 seconds
--- FAIL: TestMockDbStoreCorrect_1k (20.54s)
    common_test.go:193: testStore failed: timed out after 5 seconds

Note: The unit for time ('s') will be appended automatically by
`fmt.Errorf()`.