rpc/client: check the context before sending message
We observe failure in TestEthClient/TxInBlockInterrupted which can be reproduced
by

	go test -test.v -run=^TestEthClient/TxInBlockInterrupted --count=100

	=== RUN   TestEthClient/TxInBlockInterrupted
	    ethclient_test.go:399: transaction should be nil
	--- FAIL: TestEthClient (0.03s)

The testcase expects to get context cancel error when cancelling context passed
to the ethclient call before doing the call. However, the rpc client's send does
not guarantee that order. It uses select to wait on sending action and
context.Done() simultaneously, so it is possible that the branch of sending
action is taken and we get the response without error. This commit adds a
non-blocking wait on context.Done() to catch the cancelled context before doing
the actually send.