crypto/secp256k1: remove useless code
`(void)data;` may cause link error on Windows.

LOG:
```
\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
\Temp\go-link-676803019\000003.o: In function `default_error_callback_fn':
\go\src\github.com\ethereum\go-ethereum\crypto\secp256k1/./libsecp256k1/src/secp256k1.c:41: undefined reference to `__getreent'
\Temp\go-link-676803019\000003.o: In function `default_illegal_callback_fn':
\go\src\github.com\ethereum\go-ethereum\crypto\secp256k1/./libsecp256k1/src/secp256k1.c:30: undefined reference to `__getreent'
collect2.exe: error: ld returned 1 exit status
```