ethclient: fix the transaction in block testcase
We observe failure in TestEthClient/TxInBlockInterrupted which can be reproduced by

	go test -test.v -run=^TestEthClient/TxInBlockInterrupted --count=100

	=== RUN   TestEthClient/TxInBlockInterrupted
	    ethclient_test.go:399: transaction should be nil
	--- FAIL: TestEthClient (0.03s)

This commit removes this part of testcase where the context is canceled before
the client call and expects to get the context canceled error. It is because the
client does not guarantee to prioritize context check before client call. This
commit also adds some checks by use client.TransactionInBlock to query
transactions in test block.