swarm/storage: increase mput timeout for TestCleanIndex
The following test failed with `-race` flag on Travis.

--- FAIL: TestCleanIndex (43.85s)
    ldbstore_test.go:757: context deadline exceeded

As `-race` can increase the run time by 10x.

Alternative: we could just to increase the timeout for the
specific test. As currently the timeout is hardcoded and (strangely)
does not depend on the size of 'n'. That could be achieved by adding
a new function mputWithCustomTimeout(), but then we should keep
symmetry and add custom timeout for mget(), too. But I think the
method already has too many parameters and might be replaced by
the ongoing storage rewrite. So I won't do.